version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: snippetbox
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Password1!
